Use the "Way Back Machine" to retrieve the full-upgrade option used with the previous full-upgrade script
Quoting Isaac Asimov:

"There once was a lady named Bright,
 Who's speed was exceedingly spright,
 She stepped out one day, in a Relative way,
 And returned the previous night."

Or in the words of Dennis Ritchie:

/ * If the new process paused because it was
  * swapped out, set the stack level to the last call
  * to savu(u_ssav).  This means that the return
  * which is executed immediately after the call to aretu
  * actually returns from the last routine which did
  * the savu.
  *
  * You are not expected to understand this.
  */

diff --git a/scripts/full-upgrade b/scripts/full-upgrade
--- a/scripts/full-upgrade
+++ b/scripts/full-upgrade
@@ -17,36 +17,40 @@ $0 must be run with one of the following options:
        Due to package dependencies some user added packages may not
         function properly.
   -i : The user will be prompted to answer all questions generated by
-        packages during the upgrade. 
+        packages during the upgrade.
 EOF
 }
 
 cd /tmp
 
-case "$1" in
+OPTION="$1"
+[ "$OPTION" ] || OPTION=`ps l|grep 'full-upgrade -'|sed 's,.*full-upgrade ,,'`
+case "$OPTION" in
  -i )
-	download-only || exit $?
-	/opt/vyatta/bin/_full-upgrade $*
+	download-only "$OPTION" || exit $?
+	/opt/vyatta/bin/_full-upgrade $OPTION
 	;;
 
  -r | -k  )
-	download-only || exit $?
+	download-only "$OPTION" || exit $?
 	if ! mkdir full-upgrade.lock
 	then
-		echo "full-upgrade can't acquire it's lock file (/tmp/full-upgrade)."
+		echo "full-upgrade can't acquire it's lock file (/tmp/full-upgrade.lock )."
 		echo "You may be attempting to run full-upgrade more than once simultaneously."
-		echo "If you want to proceed, then first rm -rf /tmp/full-upgrade."
+		echo "If you want to proceed, then first rm -rf /tmp/full-upgrade.lock ."
 		exit 1
 	fi
 	echo "Please wait.  Now entering unattended mode."
 	echo "This will take a long time.  When done,"
 	echo "the system will automatically reboot."
-	hupfile=/root/nohup.out
+	hupfile=/root/nohup$$.out
+	rm /root/full-upgrade*
 	>/root/full-upgrade.log
-	tail -f /root/full-upgrade.log&
-	nohup /opt/vyatta/bin/_full-upgrade $*>&$hupfile
+	ln -s /root/full-upgrade.log /root/full-upgrade$$.log
+	tail -f /root/full-upgrade$$.log&
+	nohup /opt/vyatta/bin/_full-upgrade $OPTION>&$hupfile
 	sleep 10
-	cat /root/nohup.out
+	cat /root/nohup$$.out
 	rm -rf full-upgrade.lock
 	;;
 
