* tighten check for parent full-upgrade process * perform basic checks before starting full-upgrade * implement policy-rc.d at the begining of install-only

diff --git a/scripts/full-upgrade b/scripts/full-upgrade
--- a/scripts/full-upgrade
+++ b/scripts/full-upgrade
@@ -21,7 +21,8 @@ EOF
 
 stop_parent_fullupgrade() {
  # need to stop parent full-upgrade script if one exists
- array=(`ps ax | grep full-upgrade | grep -v grep | awk {'print $1'}`)
+ array=(`ps ax | grep "/usr/bin/full-upgrade\|/opt/vyatta/bin/full-upgrade" \
+	| grep -v grep | awk {'print $1'}`)
  len=${#array[*]}
  i=0
  while [ $i -lt $len ]; do
@@ -32,8 +33,78 @@ stop_parent_fullupgrade() {
  done
 }
 
+# picked up from install-system script
+get_response () {
+  ldefault=$(echo "$1" | tr [:upper:] [:lower:])
+  loptions=$(echo "$2" | tr [:upper:] [:lower:])
+
+  # get the response from the user
+  read myresponse
+  myresponse=$(echo "$myresponse" | tr [:upper:] [:lower:])
+
+  # Check to see if the user accepts the default
+  if [ -z "$myresponse" ]; then
+    echo -n $ldefault
+  # if we are passing in options to check, make sure response is a valid option
+  elif [ -n "$loptions" ]; then
+    for token in $loptions
+      do
+        if [ "$token" == "$myresponse" ]; then
+          echo -n "$myresponse"
+          return 0
+        fi
+      done
+    return 1
+  else
+    echo -n "$myresponse"
+  fi
+
+  return 0
+}
+
+check_repo() {
+
+# check if you have more than one repo configured in sources.list
+# if yes, advise user and ask if user wishes to continue?
+num_repos=`cat /etc/apt/sources.list | awk {'print $1'} | grep "^deb$" | wc -l`
+if [ "$num_repos" -gt "1" ]; then
+ response=''
+ while [ -z "$response" ]
+  do
+   echo "full-upgrade process detected multiple repositories to get packages from"
+   echo "unless specified in release notes, this is advised against during full-upgrade"
+   echo -ne "Would you like to continue anyway? (Y/N) [N]: "
+   response=$(get_response "N" "Y N")
+   if [ "$response" == "n" ]; then
+    exit 0
+   fi
+  done
+fi
+
+# simulate apt-get update and report error if any
+apt-get --simulate update >/dev/null 2>&1
+if [ `echo $?` != 0 ]; then
+ echo "username/password incorrect or repository not configured accurately"
+ exit 1
+else
+ apt-get --simulate update >/tmp/$$-sim-apt-update 2>&1
+ count_failed=`grep -i 'FAILED' /tmp/$$-sim-apt-update | wc -l`
+ if [ "$count_failed" != "0" ]; then
+  echo "unable to resolve repository url or connect to repository"
+  rm -f /tmp/$$-sim-apt-update
+  exit 1
+ fi
+fi
+}
+
 trap stop_parent_fullupgrade INT TERM EXIT
 
+if [ `whoami` != 'root' ] ; then
+    echo "full-upgrade must be run with root privileges."
+    exit 1
+fi
+
+check_repo
 cd /tmp
 check-upgrade $*
 
